### ISSUE TITLE
duplicate apt install command

### ISSUE THREAD

**Issue by saisona** [btungut/azure-devops-agent-on-kubernetes#16]
https://github.com/btungut/azure-devops-agent-on-kubernetes/blob/79689ca0cd44686e139701cd10218208bb405576/Dockerfile#L36

Hi, I've looked at your new docker file for v2.0.0 and noticed that you've installed `apt-transport-https' and `software-properties-common' twice.

Was this on purpose? If so, I'd like to better understand the reason, and if not, is it just a simple duplicate?

**Comment by btungut** [comment]
Changes have been merged into **release/v2.0.1** branch.
Please visit : https://github.com/btungut/azure-devops-agent-on-kubernetes/commit/b8175eed1d66a004d7cb9ae636e56768d35e4c58
