### ISSUE TITLE
UsePythonVersion@v0 does not work with selft-hosted agent

### ISSUE THREAD

**Issue by saisona** [btungut/azure-devops-agent-on-kubernetes#17]
Hi, 

If you're using the UsePythonVersion task from Microsoft on a [Self hosted agent](https://learn.microsoft.com/en-us/azure/devops/pipelines/tasks/reference/use-python-version-v0?view=azure-pipelines#how-can-i-configure-a-self-hosted-agent-to-use-this-task) following the documentation you need to handle the installation of python on you own.

Since I've found a way to make the UsePythonVersion@v0 working with my Agent I thought you might want to add my script or maybe improve it.

**Comment by btungut** [comment]
@saisona actually I have never really explored py and pip. Are they adequate and effective for Python tasks? If not, perhaps we should consider other options.
