### ISSUE TITLE
Docker build failing

### ISSUE THREAD

**Issue by widdix123** [btungut/azure-devops-agent-on-kubernetes#20]
Starting: Build an image
==============================================================================
Task         : Docker
Description  : Build or push Docker images, login or logout, start or stop containers, or run a Docker command
Version      : 2.231.0
Author       : Microsoft Corporation
Help         : https://aka.ms/azpipes-docker-tsg
==============================================================================
Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
/usr/bin/docker pull node:12.18.1
/usr/bin/docker inspect node:12.18.1
[]
/usr/bin/docker build -f /azp/_work/1/s/app/Dockerfile --label com.azure.dev.image.system.teamfoundationcollectionuri=https://dev.azure.com/abhishekgupta0696/ --label com.azure.dev.image.system.teamproject=devops-learning --label com.azure.dev.image.build.repository.name=devops-learning --label com.azure.dev.image.build.sourceversion=92ec1cc1737e514cc2523c3951bbd3776bef275e --label com.azure.dev.image.build.repository.uri=https://abhishekgupta0696@dev.azure.com/abhishekgupta0696/devops-learning/_git/devops-learning --label com.azure.dev.image.build.sourcebranchname=main --label com.azure.dev.image.build.definitionname=devops-learning --label com.azure.dev.image.build.buildnumber=20240226.1 --label com.azure.dev.image.build.builduri=vstfs:///Build/Build/11 --label image.base.ref.name=node:12.18.1 -t pipelines-javascript-docker:11 /azp/_work/1/s/app
ERROR: Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
##[error]ERROR: Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
##[error]The process '/usr/bin/docker' failed with exit code 1
Finishing: Build an image

**Comment by btungut** [comment]
@widdix123 @karabasosman could you please share the values you've provided to helm install/upgrade action. 

**Please be aware of that** you should provide `volume` and `volumeMounts` like the way implemented at below link.
Example: https://github.com/btungut/azure-devops-agent-on-kubernetes/blob/master/test/docker-supported-values.yaml

In this approach, Docker should be present in host machine.
