### ISSUE TITLE
Extending agent is not working. Sudo is missing.

### ISSUE THREAD

**Issue by matusmala** [btungut/azure-devops-agent-on-kubernetes#26]
Hello, we are using the azure-devops-agent with version 2.0.0 and extending it with Java. This is not working with new 2.0.1 version, because there is no way to install java - as sudo is disabled in this version.

Is it on purpose?

**Comment by btungut** [comment]
Hi @matusmala,

Sorry for the problem you have been experiencing; could you please share the method and details of how you used this repo to install java at 2.0.0 and not working at 2.0.1?

**Comment by btungut** [comment]
Hi @matusmala,

Please disregard my previous message and try the newly released version **v2.1.0**.
This version includes the **sudo** permissions you requested and previously had. Additionally, if you have mounted the **docker.sock**, it will grant you the necessary permissions for that as well!

**Comment by btungut** [comment]
<img width="772" alt="image" src="https://github.com/user-attachments/assets/35684ccd-1954-430c-b628-e286850582bf" />

**Comment by matusmala** [comment]
Nice, thanks!
